### ISSUE TITLE
training data and training method for the GNN model?

### ISSUE THREAD

**Issue by MachineGUN001** [HassounLab/GNN-SOM#2]
Thanks for providing interesting GNN models for metabolic loci testing. Could you please provide the training data and the relevant codes for training the GNN model?

many thanks

Sh-Y

**Comment by vporokhin** [comment]
Unfortunately we are not at liberty to share the dataset because it is derived from the RPAIR database obtained by us under an academic license. The training code is heavily dependent on this data and as such is not a part of the repository; however, we do provide detailed description of the method in [our paper](https://doi.org/10.1093/bioinformatics/btad089). To gain access to the RPAIR dataset, we suggest contacting [KEGG](https://www.kegg.jp/).

**Comment by vporokhin** [comment]
@MachineGUN001, we'll be happy to help you with setting up the model for training. If you're interested, please send us an email: soha (at) cs.tufts.edu. We look forward to hearing from you.
